packages:
  - "reporter"
  - "examples/*"
  - "packages/*"
  - "docs"
allowBuilds:
  '@parcel/watcher': true
  cypress: true
  edgedriver: true
  esbuild: false
  geckodriver: false
  msw: false
  sharp: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.0'
  - framer-motion@12.39.0
  - motion-dom@12.39.0
  - motion-utils@12.39.0
  - motion@12.39.0
