packages:
  - "reporter"
  - "examples/*"
  - "packages/*"
  - "docs"
allowBuilds:
  '@parcel/watcher': true
  cypress: true
  edgedriver: true
  esbuild: false
  geckodriver: false
  msw: false
  protobufjs: true
  sharp: true
minimumReleaseAge: 1440
trustLockfile: true
