name: Test multiple-cucumber-html-reporter

on:
  push:
    branches:
      - main
    paths:
      - reporter/**

  pull_request:
    branches:
      - main
    paths:
      - reporter/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - name: Setup Node.js v24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v5
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            node_modules
            docs/node_modules
            examples/cypress/node_modules
            examples/playwright/node_modules
            examples/wdio/node_modules
            reporter/node_modules
            reporter/dist
          key: ${{ runner.os }}-pnpm-store-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Format Check
        run: pnpm format

      - name: Lint Check
        run: pnpm lint

      - name: Build Project
        run: pnpm build
        working-directory: reporter

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - name: Setup Node.js v24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Restore dependencies cache
        uses: actions/cache/restore@v5
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            node_modules
            docs/node_modules
            examples/cypress/node_modules
            examples/playwright/node_modules
            examples/wdio/node_modules
            reporter/node_modules
            reporter/dist
          key: ${{ runner.os }}-pnpm-store-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
          fail-on-cache-miss: true

      - name: Install Root Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run Unit Tests and generate coverage report
        run: pnpm unit.test.coverage
        working-directory: reporter
