name: Test multiple-cucumber-html-reporter

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - name: Setup Node.js v24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format Check
        run: pnpm format

      - name: Lint Check
        run: pnpm lint

      - name: Build Project
        run: pnpm build
        working-directory: reporter

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - name: Setup Node.js v24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install Root Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm build
        working-directory: reporter

      - name: Run Unit Tests and generate coverage report
        run: pnpm unit.test.coverage
        working-directory: reporter
