name: Test Cypress Example

on:
  push:
    branches:
      - main
    paths:
      - examples/cypress/**
      - reporter/**

  pull_request:
    branches:
      - main
    paths:
      - examples/cypress/**
      - reporter/**

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install Root Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm build
        working-directory: reporter

      - name: Install Cypress
        working-directory: examples/cypress
        run: pnpm cypress install

      - name: Run Cypress
        working-directory: examples/cypress
        run: pnpm test
        continue-on-error: true

      - name: Generate Report
        working-directory: examples/cypress
        run: pnpm report

      - name: Upload Report
        uses: actions/upload-artifact@v7
        with:
          name: cypress-report-${{ matrix.os }}
          path: examples/cypress/.run/html-report
